### ISSUE TITLE
Upgradesettings

### ISSUE THREAD

**Issue by sfleussu** [moodleou/moodle-qtype_pmatch#42]
Hello,
When upgrading to version 20190712, the upgradesettings.php show an empty list of new **settings.**
The only BAD way I found to overpass this is to comment the 3 last lines in settings.php concerning  \qtype_pmatch\admin\qtype_pmatch_admin_setting_spell_check_languages .
We try on a quite empty instance of 3.7dev (20190418), the same in 3.7.1+ (20190725) and another on Moodle 3.6.3+ (Build: 20190418) and the same occurs.  We were using pmatch version 2019021986

![CopieMiseAjour-qtype_pmath-2019071200_from_2019021986](https://user-images.githubusercontent.com/26654616/62066091-b1a3ff00-b230-11e9-9d03-c0e52775e90a.jpg)

Thanks for any help.

**Comment by timhunt** [comment]
That's annoying. I wonder why we did not see that?

I also wonder whether, fundamentally, it is a bug in Moodle core's upgrade mechanism? I mean, if there is no setting to set, whey show the upgradesettings.php page? Of course, what this plugin is doing is quite special, so if it is a bug in Moodle, then it is quite an obscure one, and it is probably up to us to work-around it. I don't have time to investigate further now, but I will try to look later.

**Comment by jmbragg** [comment]
Just ran into this as well.  Tim, I'm sure you missed this because you wouldn't do what I just did and be lazy by upgrading via the web interface...

I did a little hunting on similar errors before I found this report and found that there were frequently typos that caused the issue similar to https://moodle.org/mod/forum/discuss.php?d=365353#p1512577

**Comment by jgupta** [comment]
We found it too while upgrading from a previous version of the plugin. It does not appear to be present on a new installation.

**Comment by Nullmann** [comment]
This is the exact same behaviour for us.

**Comment by ewout** [comment]
I had this problem and traced it no not having aspell installed on the server. [This line]( https://github.com/moodleou/moodle-qtype_pmatch/blob/master/classes/local/spell/qtype_pmatch_pspell_spell_checker.php#L64)  asks for the install aspell dicts, and if there are none, no language options are returned.

Maybe it would be a good idea to give a hint ("install aspell") in case no languages are returned.

**Comment by timhunt** [comment]
Solution seems to be to add a dummy choice to the the setting if there is not a real one.

**Comment by ewout** [comment]
Wait, there was another problem, in addition to the one above: in one of my Moodles the configuration settings in the table ```mdl_config_plugins``` had the row
```qtype_pmatch | spellchecker | null```
I do not recall how exactly the settings got in that state, but if they are, the symptoms are the same: no options for the languages, and you get stuck in upgradesettings.

**Comment by timhunt** [comment]
Have you tried my lastest fix?

**Comment by ewout** [comment]
I just upgraded to 2019082200 and can confirm that the ```spellcheck_languages``` setting is now correctly set (to empty):
![Screenshot from 2019-08-22 18-00-16](https://user-images.githubusercontent.com/6329/63549664-39ff8200-c507-11e9-92a1-2f6df5548d0b.png)

I still have problems with the ```spellchecker = null``` but I now realize that's because I have problems installing php-pspell. 

All good so far!
